### PR TITLE
Models

### PR DESCRIPTION
**Pull request by LinguList**
This PR proposes a new handling of inventories that will also be in line with further integration with Lexibank.

That means: an inventory is a collection of phonemes, phonemes are sounds in a given language, so they have an attribute "sound", which is a CLTS sound, but they are "more", as they apply to a given language and can also have occurrence and other attributes. In this form, a phoneme inventory is a collection of phonemes, and phonemes are specific kinds of sounds.

The methods for comparing inventories have been simplified, we have now two methods, one `strict_similarity` and one `approximate_similarity`.

### CODE REVIEW

**Review by xrotwang — APPROVED** [review]
Looks ok. Does this still work with 1.x version of clts-data?

**Comment by LinguList** [comment]
Unfortunately, we have lost backwards-compatibility since the last 1.x release. The reason was that we had to change feature types (feature values are okay), and they are hard-coded into the sound classes in `models.py`. So this MUST be published as a new version that is backwards incompatible.

**Comment by LinguList** [comment]
Ah, and @cormacanderson gave his okay with respect to the sounds, so we would not modify the feature system more now (we have 38 feature types and many more distinct values, so it is already pretty complex).

**Comment by LinguList** [comment]
I'll add a few more tests before merging, so we have this also covered in the future.

**Pull request merged**
