### PR TITLE
update dataset

### PR DESCRIPTION
**Pull request by LinguList**
@xrotwang, I am adding one more test for clts data here, which I consider important, as it allows to check if a given transcription dataset in the `sources` has been properly explicitly coded. This adds one more step to the workflow:

```
$ clts map sources/TD/graphemes.tsv
$ MANUAL EDITING
$ clts test_dataset TD
$ clts add_dataset TD
```

If an improper mapping is encountered (either not passing `valid_sound` or not yielding an unknown sound, this now also raises an error. The whole check routine for new transcription data was now added to one single function that is recycled in `make_pkg` which should only be used upon the final release. This yields more consistency, I hope.

### CODE REVIEW

**Comment by LinguList** [comment]
@xrotwang, I have no idea why the tests fail: they pass on my system, and the error message is all but clear to me...

**Comment by xrotwang** [comment]
The `make_dataset` command requires lingpy. So you'd need to add `lingpy` to the test deps in `setup.py`.

**Comment by LinguList** [comment]
Ah, okay, then I remove it for now. Sorry, I didn't really this.

**Comment by xrotwang** [comment]
But you can leave the test in - just add `lingpy` here: https://github.com/cldf-clts/pyclts/blob/956b07297b1402c39403b7c40e8f32d4eb24bae9/setup.py#L35-L40

**Comment by LinguList** [comment]
Yes, but it was stupid from me, since lingpy is not even required in these lines, so I removed them now, and we have the advantage of having quicker tests. It was any way onlly dead code that I added there...

**Comment by LinguList** [comment]
Okay, I just updated the test_data.tsv, which is now in concordance with the updates we made (including some changes in the features, and the like).

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
