### PR TITLE
Drafting support for multithongs and multisegment clusters

### PR DESCRIPTION
**Pull request by tresoldi**
This PR has the minimum changes for adding support for multithongs and multisegment consonant clusters to `pyclts`, as discussed mostly with Cormac and demanded by the SoundComparisons' group.

My suggestion is to allow such complex characters in code, with new classes, being fairly restrictive in terms of the consonantal clusters. Even so, I would not add those to BIPA for the time being: people who need such sounds can always have their own transcription systems where the acceptable multisegment sounds are essentially white-listed. In fact, please note that I have not added support on generation of these sounds from the names, which can be done later.

### CODE REVIEW

**Comment by tresoldi** [comment]
Cannot assign reviewers; pinging @xrotwang and @lingulist

**Comment by LinguList** [comment]
I am not sure if I like this, as I made clear to Cormac that there is no convincing case to add them. So I would say: if support is added, then in a class that does not modify any of the existing contents, so complexsound should not be touched as a class. 

I also suggest to have a full-fledged proposal in terms of features. E.g., a triphthong has three sounds, so they should be addressed as first_sound, second_sound, third_sound, etc.

**Comment by tresoldi** [comment]
There are only two cases that could be convincing, considering where CLTS is used. One is going for a 100% coverage of Phoible, which is not really important or necessary. The second is SoundComparisons, as they have many triphthongs (particularly in Germanic) and some multisegment consonant clusters, and the lack of support in CLTS was mentioned as one of the obstacles for full CLDF/Lexibank integration.

As for the code, I was trying to keep it as close and unaltered as possible, but could of course adjust. No point in doing that if there is no agreement on the overall proposal, however: I'll write to @cormacanderson (it seems I'm unable to ping him here) and ask to join the discussion.

**Comment by LinguList** [comment]
Sound comparison does not have triphthongs, it has unsegmented sounds. My argument in that discussion was exactly that scholars should start and think what the major structure of multi-vowel-sequences is. In Germanic, all cases of triphthongs can be better resolved to diphthongs plus vowel or similar. It also enhances alignments. Even in Chinese, I resolve to glide + dipthong now, so unless I get a convincing number of examples, I won't accept this.

The obstacle for integrating sound comparisons is missing orthography profiles.

**Comment by LinguList** [comment]
Furthermore, if we go this way, the PR needs to be complete, including tests and the like. It should also be backed by broad support in any of the datasets that shows triphthongs. 

As CLTS often misinterpretes sounds as clusters that were improperly segmented, I would be VERY careful by adding even more complexity without a concrete usecase (e.g., Germanic, but here, again, I think one can resolve to diphthongs, as I mentioned above).

**Comment by LinguList** [comment]
I'll close this for now, also since my requirement for three-segment combinations would be an extra class, that does not hack our ComplexSound class. We have now "from X to Y" as a general definition of complexsound instances. For three elements, we'd need "from X via Y to Z". As we won't have more than three (if at all), the implementation should not touch the ComplexSound, but make a new class of ComplexSound, potentially calling it "MultiSound" or whatever. In this way, the old code could be left untouched, with exception of the parsing procedure.

**Pull request closed without merging**
